# Copyright (c) 2017 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your settings file, as
# THIS FILE BY ITSELF WILL NOT WORK 
# These are the additions to get the engine up and running with the 
# default tk-apps for this environment


# krita
settings.tk-multi-setframerange.krita:
  hook_frame_operation: "{engine}/tk-multi-setframerange/frame_operations_tk-krita.py"
  location: "@apps.tk-multi-setframerange.location"
